stages:
  - build
  - deploy

build:
  image: node:lts
  stage: build
  tags:
    - aws
    - ridicorp
  script:
    - (cd resources/legal/privacy && ln -s `ls | sort -V | tail -n1` ../privacy.md)
    - (cd resources/legal/terms && ln -s `ls | sort -V | tail -n1` ../terms.md)
    - yarn install --frozen-lockfile
    - yarn build
  after_script:
    - (cd resources/legal && rm privacy.md terms.md)
  artifacts:
    paths:
      - dist/

deploy:
  image: ridibooks/gitlab-ci-docker-aws
  stage: deploy
  tags:
    - aws
    - ridicorp
  when: manual
  only:
    - master
  script:
    - aws s3 cp ./build s3://$(BUCKET_NAME)/ --cache-control immutable,max-age=100000000,public --recursive --acl public-read
    - aws cloudfront create-invalidation --distribution-id $(DESTRIBUTION_ID) --paths '/*'
