deploy:
  image: python:3-alpine
  variables:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    BUCKET_NAME: ${BUCKET_NAME}
  script:
  - apk add yarn make
  - yarn install
  - yarn run build
  - pip install awscli
  - make deploy
  only:
  - master
