stages:
  - build
  - deploy

build:
  image: node:lts
  stage: build
  script:
    - (cd resources/legal/privacy && ln -s `ls | sort -V | tail -n1` ../privacy.md)
    - (cd resources/legal/terms && ln -s `ls | sort -V | tail -n1` ../terms.md)
    - yarn install --frozen-lockfile
    - yarn build
  after_script:
    - (cd resources/legal && rm privacy.md terms.md)
  artifacts:
    paths:
      - dist/

dev:
  image: ridibooks/gitlab-ci-docker-aws
  stage: deploy
  variables:
    BUCKET_NAME: DEV_BUCKET_NAME
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
  only:
    - master
  script:
    - aws s3 sync dist s3://$BUCKET_NAME --cache-control public,max-age=31536000 --acl public-read

prod:
  extends: dev
  when: manual
  variables:
    BUCKET: PROD_BUCKET
