stages:
  - build
  - deploy

build:
  image: node:lts
  stage: build
  script:
    - (cd resources/legal/privacy && cp `ls | sort -V | tail -n1` ../privacy.md)
    - (cd resources/legal/terms && cp `ls | sort -V | tail -n1` ../terms.md)
    - (cd resources/ridi-pay/terms-of-use && cp `ls | sort -V | tail -n1` ../terms-of-use.md)
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/

dev:
  image: ridibooks/gitlab-ci-docker-aws
  stage: deploy
  variables:
    BUCKET_NAME: $DEV_BUCKET_NAME
    AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
  only:
    - master
  script:
    - aws s3 sync dist s3://$BUCKET_NAME --cache-control public,max-age=31536000
    - aws s3 cp s3://$BUCKET_NAME/index.html s3://$BUCKET_NAME/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate

prod:
  extends: dev
  when: manual
  variables:
    BUCKET_NAME: $PROD_BUCKET_NAME
    AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
